version: '3.8'
services:
  composer:
    image: composer
    container_name: composer_test.php
    ports:
      - "9001:9000"
    volumes:
      - .:/composer
    working_dir: /composer
    command: bash -c "chmod -R 777 . && composer install && composer dump-autoload"
