version: '3.8'
services:
  composer:
    image: composer
    container_name: composer-fortuna
    ports:
      - "9001:9000"
    volumes:
      - .:/composer
    working_dir: /composer
    command: bash -c "chmod -R 777 . && composer install --dev && composer dump-autoload"

  apache:
    build: .
    image: php7.4-apache-server
    container_name: php-server-fortuna
    volumes:
      - .:/var/www/fortuna
    ports:
      - "8083:80"
    depends_on:
      - composer

  db-mysql:
    image: mysql:8.0
    container_name: db-mysql-fortuna
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3359:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: some_root_password_should_be_here
